

# Basic Site Settings
baseurl: ""  # keep blank for user.github.io sites
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "Xinyu Li"
title_separator          : "-"
description              : &description "Ph.D. Candidate at University of Texas at Austin"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://Levilixinyu.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",

author:
  # Biographic information
  avatar           : "/images/headshot.jpg"
  name             : "Xinyu Li (李心钰）"
  bio              : "Ph.D. Candidate in Neuromuscular Physiology"
  location         : "Austin, TX"
  employer         : "University of Texas at Austin"
  email            : "xinyul@utexas.edu" 

  # Academic websites
  UT Profile       : "https://education.utexas.edu/student/xinyu_li/"
  googlescholar    : "https://scholar.google.com/citations?user=s2OLwSsAAAAJ&hl=en"
  researchgate     : "https://www.researchgate.net/profile/Xinyu-Li-196"
 
# Appearance
theme_skin: "contrast"
primary_color: "#0b2545"     
accent_color: "#d4af37"    
markdown: kramdown
paginate: 5

# These settings control the types of collections used by the template
collections:
  research:
    output: true
  publications:
    output: true
  teaching:
    output: true
  life:
    output: true
  gallery: 
    output: true


# Publication Category - The following the list of publication categories and their headings
publication_category:
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'


# Analytics
include:
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - tmp
  - README
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
highlighter: rouge


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control how pages and collections are included in the site
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # Research collection
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true

  # Publications collection
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

  # Teaching collection
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true

  # Life collection (for personal stories, reflections, or milestones)
  - scope:
      path: ""
      type: life
    values:
      layout: single
      author_profile: true
      share: true

  # Gallery collection (for photos, figures, lab or conference images)
  - scope:
      path: ""
      type: gallery
    values:
      layout: single
      author_profile: false
      share: false

# Outputting
permalink: /:categories/:title/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


